### ISSUE TITLE
Publish on Chrome App store

### ISSUE THREAD

**Issue by ahuff44** [prozz/ogs-notifier#5]
Hi! I love the extension- it's simple and does exactly what it needs to. It's also interesting to look through the code, since I've never made a chrome extension before.

Anyway, is there a reason that this isn't published on the chrome web store? As far as I can tell the process seems pretty easy; the only major hassle I can see is a [one-time $5 fee](https://developer.chrome.com/webstore/publish#pay-the-developer-signup-fee).

I feel a little queasy on principle installing a chrome extension through the developer channel like you suggest in the README...

**Comment by traveller42** [comment]
It also works better than the other notifier on the Chrome App Store.

**Comment by prozz** [comment]
well, i guess reason is because im a programmer and im used to hacking.

to be honest im not very familiar with chrome web store and lacking time to publish it properly, so if there is any developer that want to do it, as long as extension will still cost nothing, please do it! :)

**Comment by prozz** [comment]
also... no one really challenged me so i wasnt aware is broadly used :P

**Comment by traveller42** [comment]
I can look into this.

This extension is at least as good as what is already on the Chrome App Store.

I'll create a fork, but I will feature your base repo prominently in the documentation.

**Comment by prozz** [comment]
thats great to hear @traveller42 :)
best regards.

**Comment by Spoekenkieker** [comment]
Are you talking about this: https://chrome.google.com/webstore/detail/online-gocom-notification/npjhhihdmebkcbdahkpgpemfijpmdojb ?

I’m currently using both next to each other to check which I like better :-D
(and I also commented there about my colour preferences)

**Comment by traveller42** [comment]
That is the one I was referring to.

My plan is to release the current version as is and take it from there.

**Comment by Spoekenkieker** [comment]
Ideally (IMHO, but what do I know about co-operation between “competing” developers ;-) ) you folks would throw your stuff together … the other one has a feature this here one doesn’t (showing total No. of games), and this one has options the other one doesn’t have (what to open upon clicking)
___
(BTW I changed my review there to “English” so now it should be visible to you w/o having to select “all languages”)

**Comment by traveller42** [comment]
Thanks.

I think having a choice is good.  I also think there should be more than one source to provide some robustness should one or the other developer stop supporting their app.

**Comment by Spoekenkieker** [comment]
I work in a different business, but I can definitely understand becoming attached to my own products. The latter point, though, robustness, could probably also be addressed by a _group_ of devs sharing resp. co-operating on a project.

BTW, I don't understand what you mean by “take it from there” two comments above.

BTW #2: I’ll happily donate something for the help that this extension is for me if you have PayPal :-)
___
In any case, keep in mind that “Old love doesn’t rust.” (German proverb; and I still remember Eudora fondly) ;-)

**Comment by traveller42** [comment]
In this case, "take it from there" means I have no specific plan beyond getting the extension published.

I can see if the other dev is interested collaboration, but I also want to move forward.

I have many friends who also remember Eudora fondly.

**Comment by traveller42** [comment]
I've published [my fork](https://github.com/traveller42/ogs-notifier) on the [Chrome Store](https://chrome.google.com/webstore/detail/ogs-notifier/fcoiihedkoepncejhcojgooljcflgpki).

This is based on the new commit I created and tagged as Version 1.0.0.

I've also enabled Issues directly against that repo as that is where I direct folks from the Store.

@Spoekenkieker, another consideration is that this is the Round Tuit I needed to get set up for Chrome Store publishing and to start working with GitHub Pages.

**Comment by traveller42** [comment]
@ahuff44 : Is this good enough to consider your request met?

**Comment by prozz** [comment]
good job, thanks!

**Comment by Spoekenkieker** [comment]
Very cool, thank you!

**Comment by ahuff44** [comment]
thank you! ^^
